### ISSUE TITLE
Check whether ISO-8859-1 should still be enforced for .properties files

### ISSUE THREAD

**Issue by RandomByte** [SAP/ui5-server#7]
## Expected Behavior
See https://github.com/SAP/connect-openui5/issues/20

While this might be incompatible to current applications and libraries, we should look into it. A project setting might be already sufficient.

## Current Behavior
`.properties` files are always served with charset `ISO-8859-1` ([relevant code](https://github.com/SAP/ui5-server/blob/d0e747d598b8f6696755581582f53e276260c72c/lib/middleware/serveResources.js#L37)).

## Steps to reproduce the issue
1. Serve the openui5-sample-app
2. In the network trace, check the `Content-Type` header of the requested i18n file:
  ![screen shot 2018-05-23 at 18 44 55](https://user-images.githubusercontent.com/1589939/40438877-923acc8c-5eb9-11e8-9446-3f72340f7064.png)

## Context
- OS/Platform: macOS 10.13.4
- Node.js Version: v8.11.1
- npm Version: 5.8.0
- Browser *(if relevant)*: Chrome 67
- Other information: -

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [x] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by cschuff** [comment]
Since it is still [Java default behaviour](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html) to expect .properties files in `ISO-8859-1` I would stick to this behaviour. 

Storing .properties files in any other encoding could easily break things in other (productive) enviroments. Therefore I'd prefer to fail early. This should encourage people to to store their .properties files in `ISO-8859-1` and to encode special characters with `\uXXXX` syntax. This is what any intelligent editor would do anyways.

BTW: Files can be converted easily with [Java tooling](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/native2ascii.html):
`native2ascii -encoding UTF-8 i18n-UTF8.properties i18n.properties`

**Comment by matz3** [comment]
See https://github.com/SAP/ui5-tooling/pull/168

**Comment by RandomByte** [comment]
With UI5 CLI [`v1.7.0`](https://github.com/SAP/ui5-cli/releases/tag/v1.7.0), you can now configure `UTF-8` as the source encoding of a projects `*.properties` files. The default stays at `ISO-8859-1`. In both cases the UI5 Tooling will escape any non-ASCII characters, so that the build result is independent from the encoding.

📖 [Documentation](https://sap.github.io/ui5-tooling/pages/Configuration/#resources-optional) (see `propertiesFileSourceEncoding`)  
🔎 [Demo](https://github.com/SAP/openui5-sample-app/pull/54)
